name: Sync src to dev

on:
  push:
    branches:
      - src

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout src branch
        uses: actions/checkout@v4
        with:
          ref: src

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge src into dev
        run: |
          git checkout dev
          git merge src --no-edit

      - name: Push changes to dev
        run: git push origin dev